### ISSUE TITLE
请问您项目中的Model Architecture的图片是使用什么软件绘制的呢？

### ISSUE THREAD

**Issue by plommon** [hologerry/Attr2Font#14]
想请教一下您项目中的Model Architecture的图片是用什么软件绘制的呢？感觉非常好看，而且结构非常清晰！

**Comment by ueoo** [comment]
We used Adobe Illustrator to draw the figures in our paper.

**Comment by plommon** [comment]
> We used Adobe Illustrator to draw the figures in our paper.

谢谢您的回复，我去试一试！
