### ISSUE TITLE
hello! Are the attrfont CN and attrfont ENG datasets provided?

### ISSUE THREAD

**Issue by zj916716524** [hologerry/Attr2Font#15]
Hello. I am very interested in your experiment, and I have trained in the data set provided, and the effect is very good, so I want to further train in the Chinese data set. Is it convenient for attrfont CN and attrfont eng data set over there?

**Comment by ueoo** [comment]
The attrfont ENG dataset is already provided. The attrfont CN dataset is manually crafted based on ENG dataset as described in the paper.
We cannot provide the CN dataset since we do not have the copyright.
