### ISSUE TITLE
StyleEncoder ignores the attention parameter

### ISSUE THREAD

**Issue by chanind** [hologerry/Attr2Font#17]
The StyleEncoder class takes in a boolean `attention` param, defaulting to true, but this param is ignored and no attention is ever used: https://github.com/hologerry/Attr2Font/blob/master/model.py#L173

**Comment by ueoo** [comment]
Yeah, that's true, since we found the attention is not working as we expected, we removed the attention related code. The param is just a placeholder, please ignore it.
Thanks.
