### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'selected_attrs'

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/Attr2Font#2]
https://github.com/hologerry/Attr2Font/blob/810404b16c7d77ed012bb4b86cdddc2a9e0ddc36/main.py#L44  

used `opt.selected_attrs`  but  opt no this ！！

**Comment by ueoo** [comment]
fixed in 8fbc23376375cbe0a961f86846b700cb3f70b00d

**Comment by Johnson-yue** [comment]
3Q
