### ISSUE TITLE
dataset download error

### ISSUE THREAD

**Issue by ireneMsm2020** [hologerry/Attr2Font#20]
The dataset download link is invalidate， can you upload the dataset again?

**Comment by yizhiwang96** [comment]
> The dataset download link is invalidate， can you upload the dataset again?

Hi,
Sorry for the late reply.
New download links: [Google Drive](https://drive.google.com/file/d/1TTqAklfsAp6KOPxCVl2jktH8kN4lEmI_/view?usp=sharing), [PKU Disk](https://disk.pku.edu.cn:443/link/B95DB8CD0E11F92690DC24132E96DF2B)

**Comment by ueoo** [comment]
The dataset links are updated. 8cdac36fbea49488edc8ba105d0bfdac134b8c87
