### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/Attr2Font#3]
Hi, I can not  run "Sampling " part code .
https://github.com/hologerry/Attr2Font/blob/810404b16c7d77ed012bb4b86cdddc2a9e0ddc36/main.py#L242-L248

it occur in this part code .
And I confused L242 and L243 are the both set variable **val_attr_A_intensity** but with different value, why ?

**Comment by ueoo** [comment]
It's a typo.
We have thoroughly checked all the code, all the bugs have been fixed in a0ff3fdcc8e3c6bf74263e412ce6cabbf798462c
