### ISSUE TITLE
dataloader bug

### ISSUE THREAD

**Issue by Johnson-yue** [hologerry/Attr2Font#4]
![Screenshot from 2020-05-06 13-46-19](https://user-images.githubusercontent.com/10268274/81141722-16e70680-8fa0-11ea-9dce-72d810209ba3.png)

I try three times and got the same bug report

**Comment by ueoo** [comment]
fixed in 5dbc3969c777e1eb3a13c622c45cc46e70b13358

**Comment by Johnson-yue** [comment]
It still a bug here 
![Screenshot from 2020-05-06 18-00-09](https://user-images.githubusercontent.com/10268274/81164837-90442080-8fc3-11ea-9f3b-061687d51cb3.png)

maybe using  replace "/" with "//" in line 145

**Comment by ueoo** [comment]
fixed in b7084e032efa49871ce900c42dab33d8dc6b6dcb
