### ISSUE TITLE
Hi, Where can I download "AttrFont-CN"，I want test chinese charater like your Demostration

### ISSUE THREAD

**Issue by MINZU2018** [hologerry/Attr2Font#9]

**Comment by ueoo** [comment]
Hi, as described in the paper, the AttrFont-CN's attribute values are **'borrowed'** from the English dataset, the attribute values may be insufficient to depict the Chinese glyphs.
The main purpose of this dataset is to verify our model's generalization ability.
Therefore, the disclosure of this not polished dataset is of little significance to academia.
